src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Length(min:5,max:100)]
    private ?string $FullName = null;

    #[ORM\Column(length: 180)]
    #[Assert\Email]
    #[Assert\Length(min:2,max:180)]
    private ?string $email = null;

    #[ORM\Column(length: 100, nullable: true)]
    #[Assert\Length(min:10,max:100)]
    private ?string $subject = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $message = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $createdAt = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullName(): ?string
    {
        return $this->FullName;
    }

    public function setFullName(?string $FullName): self
    {
        $this->FullName = $FullName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

templates/parts/footer.html.twig
<footer>
    <div class="text-center mt-5 p-3" style="background-color: rgba(0, 0, 0, 0.2)">
      © 2023 Copyright:
      <a class="text-white" href="/"
         >Othen-co.com</a
        >
    </div>
</footer>

templates/parts/nav.html.twig
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{path('home')}}">Symrecipe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="{{path('home')}}">Accueil
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
              <a class="nav-link active" href="{{path('app_recipe_public')}}">Recettes Publiques</a>
        </li>
        {% if app.user %}
            <li class="nav-item">
              <a class="nav-link active" href="{{path('app_ingredient')}}">Ingrédients</a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" href="{{path('app_recipe')}}">Recettes</a>
            </li>
        {% endif %}
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto">
          {% if app.user %}
            <li class="nav-item dropdown" style="margin-right:5rem;">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{app.user.fullName}}</a>
              <div class="dropdown-menu">
                  <a class="dropdown-item" href="{{path('app_user',{id:app.user.id})}}">Modifier mes informations</a>
                  <a class="dropdown-item" href="{{path('app_user_edit_password',{id:app.user.id})}}">Modifier mot de passe</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{path('app_logout')}}">Déconnexion</a>
              </div>
            </li>
          {% else %}
              <li class="nav-item">
                <a class="nav-link active" href="{{path('app_register')}}">Inscription</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link active" href="{{path('app_security')}}">Se connecter</a>
              </li>
          {% endif %}
          
        </ul>
      </div>
    </div>
  </div>
</nav>